### PR TITLE
fix: correctly order "CI/CD" in "Gitlab CI/CD"

### PR DESCRIPTION
**Pull request by Addono**

### CODE REVIEW

**Comment by Addono** [comment]
/UNWIP

Ready to go

**Comment by Addono** [comment]
@javib51

**Comment by javib51** [comment]
@Addono Thank you! 
Sorry for the delay, I didn't see this before.

**Comment by Addono** [comment]
Yeah, I forgot you only get notified when you get pinged.

-------- Original Message --------

**Pull request merged**
